### ISSUE TITLE
what's "redit_*/*" in prepare_data/hadoop/run.sh ?

### ISSUE THREAD

**Issue by chong0412** [Anna146/HiddenAttributeModels#4]
I tried to run _run.sh_, but it said`Input Pattern hdfs://master:8020/user/root/reddit_*/* matches 0 files`    ( had put  postids.txt.gz )
I changed it into _reddit_ham_postids.txt.gz_, it still failed~

**Comment by Anna146** [comment]
first you need to download Reddit submissions from
https://files.pushshift.io/reddit/
I will provide readme for running hadoop files
