### ISSUE TITLE
ask a question

### ISSUE THREAD

**Issue by CodingPerson** [Anna146/HiddenAttributeModels#5]
if p["mode"] == "grid":
        num_folds = 10
        with open(p["grid_file"], "a+") as f_grid:
            f_grid.write("params %s\n" % (expid))
            for kk in range(num_folds):
                if kk >= max_folds:
                    break
                print("Fold number " + str(kk))
                f_grid.write("Fold number " + str(kk) + "\n")
                model.train(p["train_folder"], p["test_set"],kk=kk, folds=num_folds, grid=True, grid_file=f_grid)

As shown above, what is the meaning of KK here?What's the point of traversing over KK?thank you

**Comment by Anna146** [comment]
which file are you referring to?

**Comment by CodingPerson** [comment]
run.py

**Comment by Anna146** [comment]
this one performs grid search on 10-fold cross-validation, kk is the number of fold

**Comment by CodingPerson** [comment]
but on the run.py,why max_folds = 2? I think 10 is right

**Comment by Anna146** [comment]
Yes, just change it to ten, 2 was just for testing

**Comment by CodingPerson** [comment]
Thank you very much. Finally, if you want the best results, do I only need to run the GRID mode, but I find that the GRID mode does not have been validated, why is that?

**Comment by Anna146** [comment]
so basically this grid mode is to find the best epoch, intermediate results are written ti the output file every 10 epochs of training. After analyzing output file you select best epoch and set this param and run the test mode

**Comment by CodingPerson** [comment]
I've learned it，thanks a lot

**Comment by Anna146** [comment]
no prob at all, thnx for your interest!
